replicaCount: 1

image:
  repository: yuridiachenko/notiefy-main
  tag: latest
  pullPolicy: Always

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"

service:
  type: NodePort
  port: 8081

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/notiefy-db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
