apiVersion: apps/v1
kind: Deployment
metadata:
  name: notiefy-main-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notiefy-main
  template:
    metadata:
      labels:
        app: notiefy-main
    spec:
      containers:
      - name: notiefy-main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: {{ .Values.env.SPRING_DATASOURCE_URL }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
