apiVersion: v1
kind: Service
metadata:
  name: notiefy-main-service
spec:
  selector:
    app: notiefy-main
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8081
  type: {{ .Values.service.type }}